import NoteDAO from "./noteDAO";

export default interface Library {
    libraryName: string,
    librarian: string,
    assistant: string,
    street: string,
    district: string,
    city: string,
    county: string,
    state: string,
    zip: string,
    email: string,
    phoneNumber: number,
    extension?: string,
    level: string,
    size: number,
    dateUpdated: string,
    assignedRep: string,
    _id?: string,
    _rev?: string,
    totalSales: number,
    lastSale: number,
    dateLastSale?: string,
    dateNextContact?: string,
    notes?: NoteDAO[],
}
